<tr>
    <td align="center">
        <table class="col-600" width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="">
            <tbody>
                <tr><td height="40"></td></tr>
                <tr>
                    <td align="center">
                        <!-- Image Map Generated by http://www.image-map.net/ -->
                        <img src="https://www.adi-media.com/img/CT-LT-600x160-01.png" usemap="#image-map">

                        
                      <map name="image-map">
                            <area target="_blank" alt="adi media" title="adi media" href="https://www.adi-media.com/" coords="3,60,96,124" shape="rect">
                            <area target="_blank" alt="Home" title="Home" href="https://www.communicationstoday.co.in/" coords="29,130,85,149" shape="rect">
                            <area target="_blank" alt="About us" title="About us" href="https://www.communicationstoday.co.in/aboutus/" coords="97,133,163,153" shape="rect">
                            <area target="_blank" alt="Contact us" title="Contact us" href="https://www.communicationstoday.co.in/contact-us/" coords="171,131,240,151" shape="rect">
                            <area target="_blank" alt="Term & Conditions" title="Term & Conditions" href="https://www.communicationstoday.co.in/terms-conditions/" coords="261,132,385,150" shape="rect">
                            <area target="_blank" alt="Privacy" title="Privacy" href="https://www.communicationstoday.co.in/privacy-policy/" coords="394,129,485,151" shape="rect">
                            <area target="_blank" alt="Disclaimer" title="Disclaimer" href="https://www.communicationstoday.co.in/disclaimer/" coords="492,130,562,152" shape="rect">
                            <area target="_blank" alt="CT" title="CT" href="https://www.communicationstoday.co.in/" coords="366,16,583,40" shape="rect">
                            <area target="_blank" alt="Linkedin" title="Linkedin" href="https://www.linkedin.com/company/communications-today/" coords="418,44,449,71" shape="rect">
                            <area target="_blank" alt="Twitter" title="Twitter" href="https://twitter.com/comms_today" coords="462,44,492,74" shape="rect">
                            <area target="_blank" alt="Youtube" title="Youtube" href="https://www.youtube.com/@communicationstoday8265" coords="502,43,533,70" shape="rect">
                        </map>
                    </td>
                </tr>
                <tr><td height="20"></td></tr>
            </tbody>
        </table>
    </td>
</tr>